### ISSUE TITLE
How scale fabconnect?

### ISSUE THREAD

**Issue by thapld** [hyperledger/firefly-fabconnect#115]
Hi,
How to scale fabconnect when leveldb reach out of disk?

**Comment by nguyer** [comment]
Hi @thapld. It's a good question, but I would encourage you to ask this over in the #firefly channel in the Hyperledger Discord server https://discord.gg/Fy7MJuqw86

We use GitHub Issues for tracking specific work items like bugs or new features and we use Discord for support or general questions. Thanks!
