### ISSUE TITLE
Fabconnect websocket listener not working?

### ISSUE THREAD

**Issue by thapld** [hyperledger/firefly-fabconnect#116]
Here step by step:
1. Create event streams
![image](https://github.com/hyperledger/firefly-fabconnect/assets/38736191/12cf637e-a5c8-40d5-8440-307770485a84)
2. Subscription
![image](https://github.com/hyperledger/firefly-fabconnect/assets/38736191/19fe3ba0-e25c-4633-b08a-86d6cab11b2a)
3. wscat connect websocket
![image](https://github.com/hyperledger/firefly-fabconnect/assets/38736191/8a43adb9-e8ba-4810-97c1-aa95df2be1c6)
4. Transfer erc20 token, but nothing response in websocket client

**Comment by nguyer** [comment]
Hi @thapld. Can you please provide more details about what you are trying to do? Are you using Fabconnect with FireFly and creating your subscription, websocket connection, and making the token transfer through FireFly's API or are you just using Fabconnect by itself? Did you deploy a custom chaincode for your ERC-20 contract that emits the event you are listening for?

**Comment by thapld** [comment]
Yes, I use Fabconnect API without FireFly. And ERC-20 chaincode have a emit event when transfer.
![image](https://github.com/hyperledger/firefly-fabconnect/assets/38736191/6a9bc491-6306-4aad-bde0-c4298831e5ef)
![image](https://github.com/hyperledger/firefly-fabconnect/assets/38736191/34057e85-a92a-4009-a291-d7787fb6ac04)

**Comment by thapld** [comment]
I also try with type Transfer:
![image](https://github.com/hyperledger/firefly-fabconnect/assets/38736191/51829b46-38ff-4ac1-888a-3fce90e7618f)
![image](https://github.com/hyperledger/firefly-fabconnect/assets/38736191/5cd54fdb-dbf7-4cd9-a04d-19faa4e07753)
But nothing happen.
I wonder any wrong when I create event streams or subscription as topic (any string, right?)

**Comment by thapld** [comment]
Ok, It works:
![image](https://github.com/hyperledger/firefly-fabconnect/assets/38736191/5415da60-8cf4-458c-a2fb-a270218d5e4a)
But I only can listen one time and I have to reconnect websocket and send message again

**Comment by thapld** [comment]
solved on discord!
